# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RaceYou' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RaceYou

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'

  target 'RaceYouTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RaceYou-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RaceYou-tvOS

  target 'RaceYou-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
